"""empty message

Revision ID: 62c73f47c263
Revises: 721045c4b115
Create Date: 2018-01-11 21:19:49.004409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c73f47c263'
down_revision = '721045c4b115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aurora_config', sa.Column('status', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aurora_config', 'status')
    # ### end Alembic commands ###
